### ISSUE TITLE
[SUGGESTION] Handling floating origin

### ISSUE THREAD

**Issue by Eraile** [Prographers/Precomputed-Culling#1]
Hello to the team :)

Basically, i faced this issue with my space game... When i would stay in the a specific of my origin, everything was fine until i reached some location, too far from the center, that made the whole graphics glitch as floating was too imprecise to properly render everything on screen.

The solution to this problem is to basically, once you reach a certain distance, to offset back your player's camera (& objects & the whole world basically) & shifts it, registering this offset in a second variable.

Without this kind of mechanic, you cannot have huge worlds or universe sized worlds :)
I think this would definitely be a huge plus for your solution compared to the other solutions.

Thanks for your work!

**Comment by Muchaszewski** [comment]
Thank you for your suggestion, we will investigate it and what can we do with it! We will let you know once we find some solutions for that.

**Comment by BartoszStepienProg** [comment]
Hello Eraile,

We've improved our baking system, so now it supports moving areas with objects inside
Hope it will fixes your issue, the updated version should be available on unity asset store in about one working week.

Kind regards,
Prographers team
